source 'http://rubygems.org'

gem 'bourbon'
gem 'middleman', '3.2.2'
#, github: 'middleman/middleman', branch: 'v3-stable'
gem 'middleman-autoprefixer'
gem 'middleman-blog'
gem 'middleman-deploy', '0.1.4'
gem 'middleman-livereload', '~> 3.1.0'
gem 'middleman-pagination'
# gem 'middleman-rouge'
gem 'middleman-syntax'
gem 'neat'
gem 'redcarpet'
