source 'http://rubygems.org'

gem 'bourbon'
gem 'middleman', github: 'middleman/middleman', branch: 'v3-stable'
gem 'middleman-autoprefixer'
gem 'middleman-blog'
gem 'middleman-deploy'
gem 'middleman-livereload', '~> 3.1.0'
gem 'middleman-pagination'
gem 'middleman-rouge'
gem 'middleman-syntax', '~> 1.2.1'
gem 'neat'
gem 'redcarpet'
